import { signIn, signOut, useSession } from "next-auth/react";
import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const MainQuiz = dynamic(() => import("~/components/MainQuiz"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="">Quiz</h1>
        <MainQuiz />
      </main>
    </>
  );
}
