import dynamic from "next/dynamic";
import Head from "next/head";

const MainQuiz = dynamic(() => import("~/components/MainQuiz"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-6 flex flex-col items-center justify-center gap-6">
        <h1 className="text-4xl font-bold">Marathon preparation plan</h1>
        <MainQuiz />
      </main>
    </>
  );
}
